### ISSUE TITLE
Doubt regarding shape of EK-100 rgb_bninception feature

### ISSUE THREAD

**Issue by Anirudh257** [zhaoyue-zephyrus/TeSTra#5]
Thanks for sharing your code. I was looking into the code and downloaded the EK-100 **rgb_kinetics_bninception** features but the size is 1024 and not 2048. Is this correct?

**Comment by chcchc97** [comment]
@[Anirudh257](https://github.com/Anirudh257)Hi！I also have problem about the shape of the features. I download [THUMOS'14 **Flow (TV-L1)** feature](https://utexas.app.box.com/s/rhvihb33e54ro07zsmcbgku16cikk2g4) but the side is 2048 not 1024. Are there something wrong about the flow feature？I put the video_test_0000004 as the example as follow.
![image](https://github.com/zhaoyue-zephyrus/TeSTra/assets/60684460/2dd7a3b4-dd73-4eea-b3aa-e86198eee74f)

**Comment by Anirudh257** [comment]
Hi @Chenhongchang Yes, you are correct. It is 2048, not 1024. Make changes in the config file accordingly.

**Comment by chcchc97** [comment]
> Hi @Chenhongchang Yes, you are correct. It is 2048, not 1024. Make changes in the config file accordingly.

thank you very much.
